title: Welcome to the BencomWebApp GitHub Page!
description: A first trial-and-error approach.
theme: icarus

menu:
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about
